"""Added provider admin tables

Revision ID: 22951c5f0f0c
Revises: ec6411d99e0b
Create Date: 2026-04-15 14:50:44.448674

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22951c5f0f0c"
down_revision: Union[str, Sequence[str], None] = "ec6411d99e0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tooldbmodel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tooladminuserdbmodel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool", sa.Uuid(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tool"],
            ["tooldbmodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tooladminuserdbmodel_tool"), "tooladminuserdbmodel", ["tool"], unique=False)
    op.create_index(op.f("ix_tooladminuserdbmodel_user"), "tooladminuserdbmodel", ["user"], unique=False)
    op.create_table(
        "toolauthorisationdbmodel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tool", sa.Uuid(), nullable=False),
        sa.Column("reporting_org", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tool"],
            ["tooldbmodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_toolauthorisationdbmodel_reporting_org"), "toolauthorisationdbmodel", ["reporting_org"], unique=False
    )
    op.create_index(op.f("ix_toolauthorisationdbmodel_tool"), "toolauthorisationdbmodel", ["tool"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_toolauthorisationdbmodel_tool"), table_name="toolauthorisationdbmodel")
    op.drop_index(op.f("ix_toolauthorisationdbmodel_reporting_org"), table_name="toolauthorisationdbmodel")
    op.drop_table("toolauthorisationdbmodel")
    op.drop_index(op.f("ix_tooladminuserdbmodel_user"), table_name="tooladminuserdbmodel")
    op.drop_index(op.f("ix_tooladminuserdbmodel_tool"), table_name="tooladminuserdbmodel")
    op.drop_table("tooladminuserdbmodel")
    op.drop_table("tooldbmodel")
    # ### end Alembic commands ###
