"""Initial DB setup

Revision ID: 3f9b7ff8bb73
Revises:
Create Date: 2025-11-04 11:07:12.601312

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f9b7ff8bb73"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "finegrainedauthorisationdbmodel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=False),
        sa.Column("reporting_org", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CONTRIBUTOR", "EDITOR", "PROVIDER_ADMIN", "ADMIN", "SUPER_ADMIN", name="finegrainedauthorisationrole"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_finegrainedauthorisationdbmodel_reporting_org"),
        "finegrainedauthorisationdbmodel",
        ["reporting_org"],
        unique=False,
    )
    op.create_index(
        op.f("ix_finegrainedauthorisationdbmodel_user"), "finegrainedauthorisationdbmodel", ["user"], unique=False
    )
    op.create_table(
        "superadminuserdbmodel",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user", sa.Uuid(), nullable=False),
        sa.Column("is_superadmin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_superadminuserdbmodel_user"), "superadminuserdbmodel", ["user"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_superadminuserdbmodel_user"), table_name="superadminuserdbmodel")
    op.drop_table("superadminuserdbmodel")
    op.drop_index(op.f("ix_finegrainedauthorisationdbmodel_user"), table_name="finegrainedauthorisationdbmodel")
    op.drop_index(
        op.f("ix_finegrainedauthorisationdbmodel_reporting_org"), table_name="finegrainedauthorisationdbmodel"
    )
    op.drop_table("finegrainedauthorisationdbmodel")
    op.execute("DROP TYPE finegrainedauthorisationrole")
    # ### end Alembic commands ###
