"""add client id to tooldbmodel

Revision ID: b2c6d1170383
Revises: 22951c5f0f0c
Create Date: 2026-04-27 13:06:36.123347

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b2c6d1170383"
down_revision: Union[str, Sequence[str], None] = "22951c5f0f0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "finegrainedauthorisationdbmodel",
        "role",
        existing_type=postgresql.ENUM(
            "CONTRIBUTOR", "EDITOR", "PROVIDER_ADMIN", "ADMIN", "CONTRIBUTOR_PENDING", name="role"
        ),
        type_=sa.Enum(
            "CONTRIBUTOR",
            "EDITOR",
            "PROVIDER_ADMIN",
            "ADMIN",
            "SUPER_ADMIN",
            "CONTRIBUTOR_PENDING",
            name="finegrainedauthorisationrole",
        ),
        existing_nullable=False,
    )
    op.add_column("tooldbmodel", sa.Column("client_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tooldbmodel", "client_id")
    op.alter_column(
        "finegrainedauthorisationdbmodel",
        "role",
        existing_type=sa.Enum(
            "CONTRIBUTOR",
            "EDITOR",
            "PROVIDER_ADMIN",
            "ADMIN",
            "SUPER_ADMIN",
            "CONTRIBUTOR_PENDING",
            name="finegrainedauthorisationrole",
        ),
        type_=postgresql.ENUM("CONTRIBUTOR", "EDITOR", "PROVIDER_ADMIN", "ADMIN", "CONTRIBUTOR_PENDING", name="role"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
