import contextlib
import io
import logging
import os
import time
from typing import AsyncIterator
from uuid import UUID

import jwt
import sqlmodel
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from fastapi import FastAPI
from libsuitecrm import SuiteCRM  # type: ignore

import register_your_data_api.util as util
from main import add_routers_and_general_exception_handling
from register_your_data_api.auth.fga.fga_provider_db import (
    FineGrainedAuthorisationDbModel,
    FineGrainedAuthorisationProviderDb,
    SuperAdminUserDbModel,
)
from register_your_data_api.auth.fga.models import FineGrainedAuthorisationRole
from tests.helpers.keys import KeyDict

from ..helpers import prom
from .mocked_objects.mock_suitecrm import MockSuiteCRM
from .setup_and_teardown import setup_db


class MockKeyStore:
    """Class that mocks the functionality of the jwt.PyJWTClient key store

    This doesn't use unittest.Mock because we need to preserve functionality.

    Note I've explicitly ignored some type errors here, particularly around the typing
    of the dicts for this mock key store.
    """

    def __init__(self) -> None:
        self._keys = {}  # type: dict[str, jwt.PyJWK]

    def add_key(self, kid: str, alg: str, public_key: rsa.RSAPublicKey) -> None:
        """Add a key to the key store.

        Parameters
        ----------
        kid : str
            Id of the key to add.
        alg : str
            Algorithm that the key uses.
        public_key : rsa.RSAPublicKey
            The key itself.
        """
        numbers = public_key.public_numbers()

        n = jwt.utils.base64url_encode(numbers.n.to_bytes((numbers.n.bit_length() + 7) // 8, "big")).decode("utf-8")
        e = jwt.utils.base64url_encode(numbers.e.to_bytes((numbers.e.bit_length() + 7) // 8, "big")).decode("utf-8")

        self._keys[kid] = jwt.PyJWK.from_dict({"kid": kid, "kty": "RSA", "alg": alg, "use": "sig", "n": n, "e": e})

    def add_keys_from_dict(self, key_dict: dict[str, KeyDict]) -> None:
        """Add all the keys from a dictionary generated by keys.generate_keys

        Parameters
        ----------
        key_dict : dict[str, dict[str, bytes  |  rsa.RSAPublicKey]]
        """
        for key_id in key_dict:
            self.add_key(key_id, "RS256", key_dict[key_id]["public_key_object"])

    def get_signing_key_from_jwt(self, token: str) -> jwt.PyJWK:
        """Get the signing key id from a JWT by examining the unverified header

        Parameters
        ----------
        token : str
            Access token.

        Returns
        -------
        str
            Key id.
        """
        unverified_header = jwt.get_unverified_header(token)
        if unverified_header.get("kid", None) is None or unverified_header.get("kid") not in self._keys:
            raise jwt.PyJWKClientError("Key not found")
        return self._keys[unverified_header.get("kid")]  # type: ignore

    def get_signing_key(self, kid: str) -> jwt.PyJWK:
        """Get the signing key for a given key id.

        Parameters
        ----------
        kid : str
            The key id to fetch.

        Returns
        -------
        dict[str, bytes | str]
            Key dictionary, containig the key itself, and the algorithm.

        Raises
        ------
        jwt.PyJWKClientError
            If the key is not found in this key store.
        """
        if kid not in self._keys:
            raise jwt.PyJWKClientError("Key not found")
        return self._keys[kid]


class MockedTestContext(util.Context):

    _mocked_suitecrm_client: MockSuiteCRM

    def __init__(self, logs_to_stdout: bool = False) -> None:
        util.Context.__init__(self, logs_to_stdout=logs_to_stdout)
        self._env = {}
        self._mocked_suitecrm_client = MockSuiteCRM()

    def _setup_loggers(self) -> None:
        self._app_logger = logging.getLogger("ryd-api")
        self._app_logger.handlers.clear()
        self._app_log_file_handler = logging.StreamHandler(io.StringIO())
        self._app_log_formatter = logging.Formatter(fmt="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
        self._app_log_file_handler.setFormatter(self._app_log_formatter)
        self._app_logger.addHandler(self._app_log_file_handler)

        self._audit_logger = logging.getLogger("ryd-api-audit")
        self._audit_log_file_handler = logging.StreamHandler(io.StringIO())
        self._audit_log_formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")  # type: ignore
        self._audit_log_file_handler.setFormatter(self._audit_log_formatter)
        self._audit_logger.addHandler(self._audit_log_file_handler)

    def _setup_key_store(self) -> None:
        self._key_store = MockKeyStore()  # type: ignore

    def get_suitecrm_client(self) -> SuiteCRM:
        return self._mocked_suitecrm_client


class MockedAppAndContext:

    _JWKS_KEYS: dict[str, tuple[bytes, bytes, rsa.RSAPublicKey]]

    _app: FastAPI

    _app_is_created: bool = False

    _mocked_context: MockedTestContext

    _mocked_user_ids: list[UUID] = []

    _mocked_reporting_org_ids: list[UUID] = []

    def __init__(self) -> None:
        # Generate two test keys
        self._JWKS_KEYS: dict[str, tuple[bytes, bytes, rsa.RSAPublicKey]] = {}
        self._create_test_key("key1")
        self._create_test_key("key2")

        # Setup lists of test users and reporting orgs
        self._mocked_user_ids.append(UUID("698e0c1f-4e80-faa9-6533-68de801d1735"))  # Person One
        self._mocked_user_ids.append(UUID("bea511d3-c7a7-4097-55ed-68de81e94921"))  # Person Two
        self._mocked_user_ids.append(UUID("a1b191ee-4c12-461c-cbe1-68de8173f628"))  # Person Three
        self._mocked_user_ids.append(UUID("7625122c-f752-40dc-a577-5cb49e13de2a"))  # Person Four
        self._mocked_user_ids.append(UUID("b46b88bd-05e6-4cb8-8b6a-a2c47fcd666d"))  # Person Five
        self._mocked_user_ids.append(UUID("8c51d9bf-46c2-4d1d-869b-d9e2dd63ff48"))  # Person Six

        self._mocked_reporting_org_ids.append(UUID("552376ae-2aa7-98ab-d800-68daa9bfeb4a"))  # aid-agency-01
        self._mocked_reporting_org_ids.append(UUID("ab851a83-a384-3eb9-caf0-68db8125b067"))  # agency-02
        self._mocked_reporting_org_ids.append(UUID("da17734d-3926-47ef-8563-8a1b0247ed11"))  # gov agency 03
        self._mocked_reporting_org_ids.append(UUID("0a3a9507-d674-480e-b625-7d190f4f3319"))  # Agency Not in Mock CRM

        self._mocked_context = make_test_context(self)  # type: ignore

    def __del__(self) -> None:
        pass

    def _create_test_key(self, key_name: str) -> None:
        private_key = rsa.generate_private_key(public_exponent=65537, key_size=4096)
        public_key = private_key.public_key()
        self._JWKS_KEYS[key_name] = (
            private_key.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.NoEncryption(),
            ),
            public_key.public_bytes(
                encoding=serialization.Encoding.PEM, format=serialization.PublicFormat.SubjectPublicKeyInfo
            ),
            public_key,
        )

    def get_test_app(self) -> FastAPI:

        @contextlib.asynccontextmanager
        async def test_lifespan(app: FastAPI) -> AsyncIterator[None]:
            prom.reset_prom_registry()
            app.state.context = self._mocked_context

            for key_id in self._JWKS_KEYS:
                app.state.context.key_store.add_key(key_id, "RS256", self._JWKS_KEYS[key_id][2])

            yield

        if not self._app_is_created:
            self._app = FastAPI(title="Register Your Data", lifespan=test_lifespan)
            add_routers_and_general_exception_handling(self._app)
            self._app_is_created = True

        return self._app

    def get_valid_authorization_header(self, test_user_num: int) -> dict[str, str]:
        """Generates an authorisation header for the user specified in test_user_num

        Parameters
        ----------
        test_user_num : int
            Index of the mock test user.

        Returns
        -------
        dict[str, str]
            Standard header dictionary with a single entry for 'Authorization'
        """

        claims = make_access_token_payload(
            subject=str(self._mocked_user_ids[test_user_num]),
            audience="iati_register_your_data",
            scopes=(
                "ryd ryd:reporting_org ryd:reporting_org:create ryd:reporting_org:update ryd:reporting_org:delete "
                "ryd:reporting_org:user ryd:reporting_org:user:update ryd:dataset "
                "ryd:dataset:update ryd:dataset:delete"
            ),
        )
        token = jwt.encode(claims, self._JWKS_KEYS["key1"][0], algorithm="RS256", headers={"kid": "key1"})
        return {"Authorization": "Bearer " + token}

    def set_suitecrm_mocked_response_file(self, response_file: str) -> None:
        self._mocked_context._mocked_suitecrm_client.set_response_file(response_file)

    @property
    def app(self) -> FastAPI:
        return self._app


def make_test_context(app_and_context: MockedAppAndContext) -> util.Context:
    """Makes a mock context object for use in testing

    All required environment variables are defined in code but only
    a few are set (APP_LOG_LEVEL and AUDIT_LOG_PUBLIC_KEY_PATH) as
    these are required by the Context class to setup the loggers.
    Licences are not loaded.

    App and audit log streams are replaced with a string buffer that
    can be inspected in tests.  The key store is replaced with a mock key
    store class.

    Returns
    -------
    util.Context
    """

    test_context = MockedTestContext(logs_to_stdout=True)

    # TODO: part way through converting util.Context to use methods to set up
    # each of the components so that they can be overriden in MockedTestContext,
    # which would allow us just to call .setup() here instead of each of the
    # components.

    env_fh = open(".env", "r")
    test_context._load_and_validate_env(env_fh)
    env_fh.close()

    test_context._setup_prom_metrics()

    test_context._setup_loggers()

    test_context._setup_key_store()

    # Add sqlite FGA provider and populate with test values
    if os.path.isfile("test.db"):
        os.unlink("test.db")
    setup_db("sqlite:///test.db")
    test_context._fga_provider = FineGrainedAuthorisationProviderDb("sqlite:///test.db")
    test_context._fga_provider.setup()

    with sqlmodel.Session(test_context._fga_provider._engine) as session:

        # Pesron One / User index 0   = UUID("698e0c1f-4e80-faa9-6533-68de801d1735")
        # Person Two / User index 1   = UUID("bea511d3-c7a7-4097-55ed-68de81e94921")
        # Person Three / User index 2 = UUID("a1b191ee-4c12-461c-cbe1-68de8173f628")
        # Person Four / User index 3  = UUID("7625122c-f752-40dc-a577-5cb49e13de2a")
        # Person Five / User index 4  = UUID("b46b88bd-05e6-4cb8-8b6a-a2c47fcd666d")

        # Aid Agency 01 / index 0 = UUID("552376ae-2aa7-98ab-d800-68daa9bfeb4a")
        # Agency 02     / index 1 = UUID("ab851a83-a384-3eb9-caf0-68db8125b067")
        # Gov Agency 03 / index 2 = UUID("da17734d-3926-47ef-8563-8a1b0247ed11")
        # Agency Not in Mock CRM / index 3 = UUID("0a3a9507-d674-480e-b625-7d190f4f3319")

        # Add user 1 roles.
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[0],
                reporting_org=app_and_context._mocked_reporting_org_ids[0],
                role=FineGrainedAuthorisationRole.EDITOR,
            )
        )
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[0],
                reporting_org=app_and_context._mocked_reporting_org_ids[1],
                role=FineGrainedAuthorisationRole.ADMIN,
            )
        )

        # Person Two - admin to Aid Agency 01
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[1],
                reporting_org=app_and_context._mocked_reporting_org_ids[0],
                role=FineGrainedAuthorisationRole.ADMIN,
            )
        )
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[1],
                reporting_org=app_and_context._mocked_reporting_org_ids[2],
                role=FineGrainedAuthorisationRole.ADMIN,
            )
        )
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[1],
                reporting_org=app_and_context._mocked_reporting_org_ids[3],
                role=FineGrainedAuthorisationRole.ADMIN,
            )
        )

        # Add user 3 roles.
        session.add(SuperAdminUserDbModel(user=app_and_context._mocked_user_ids[2], is_superadmin=True))

        # Add User 4 roles
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[3],
                reporting_org=app_and_context._mocked_reporting_org_ids[0],
                role=FineGrainedAuthorisationRole.CONTRIBUTOR,
            )
        )
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[3],
                reporting_org=app_and_context._mocked_reporting_org_ids[1],
                role=FineGrainedAuthorisationRole.CONTRIBUTOR_PENDING,
            )
        )
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[3],
                reporting_org=app_and_context._mocked_reporting_org_ids[3],
                role=FineGrainedAuthorisationRole.CONTRIBUTOR_PENDING,
            )
        )

        # Add User 5 roles
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[4],
                reporting_org=app_and_context._mocked_reporting_org_ids[0],
                role=FineGrainedAuthorisationRole.PROVIDER_ADMIN,
            )
        )
        session.add(
            FineGrainedAuthorisationDbModel(
                user=app_and_context._mocked_user_ids[4],
                reporting_org=app_and_context._mocked_reporting_org_ids[1],
                role=FineGrainedAuthorisationRole.PROVIDER_ADMIN,
            )
        )

        session.commit()

    return test_context


def make_context() -> util.Context:

    context = util.Context(logs_to_stdout=True)

    # Create public key file.
    private_key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    public_key = private_key.public_key()
    public_key_fh = open("test-audit-log-public-key.pem", "wb")
    public_key_fh.write(
        public_key.public_bytes(
            encoding=serialization.Encoding.PEM, format=serialization.PublicFormat.SubjectPublicKeyInfo
        )
    )
    public_key_fh.close()

    # Set all environment variables.
    context._env = {}  # notype
    for key in context._REQUIRED_ENV_VARS:
        context._env[key] = ""
    context.env["APP_LOG_LEVEL"] = "DEBUG"
    context.env["AUDIT_LOG_PUBLIC_KEY_PATH"] = "test-audit-log-public-key.pem"

    # Setup log handlers with string buffers we can examine.
    context._setup_loggers()
    context._app_logger.handlers.clear()
    context._app_log_file_handler = logging.StreamHandler(io.StringIO())
    context._app_log_file_handler.setFormatter(context._app_log_formatter)
    context._app_logger.addHandler(context._app_log_file_handler)

    context._audit_logger.handlers.clear()
    context._audit_log_file_handler = logging.StreamHandler(io.StringIO())
    context._audit_log_formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")  # type: ignore
    context._audit_log_file_handler.setFormatter(context._audit_log_formatter)
    context._audit_logger.addHandler(context._audit_log_file_handler)

    # Setup prom metrics.
    context._setup_prom_metrics()

    # Add mock key store.
    context._key_store = MockKeyStore()  # type: ignore

    return context


def make_access_token_payload(
    subject: str = "some_subject",
    audience: str = "some_audience",
    scopes: str = "some_scope",
    expiry_delta: int = 3600,
) -> dict[str, str | int]:
    """Make a mock access token payload of claims and extra externalid attribute

    Parameters
    ----------
    subject : str, optional
        Subject for the claim, by default "some_subject"
    audience : str, optional
        Audience for the claim, by default "some_audience"
    scope : str, optional
        Scopes to add to the claim, by default "some_scope"
    expiry_delta : int, optional
        Time offset from the moment of invocation to add to the expiry time, by default +3600 seconds.

    Returns
    -------
    dict[str, str | int]
    """
    return {
        "sub": subject,
        "iatiRegistryId": subject,  # for the automated tests, set these to the same
        "name": "some_user_name",
        "aud": audience,
        "scope": scopes,
        "exp": int(time.time()) + expiry_delta,
    }
